# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0006_delete_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='about',
        ),
    ]
